#!/bin/bash

echo 'Building vzcontrol'

if [ ! -d "./out" ]; then
    echo 'Making output directory'
    mkdir ./out
    cp ./conf/config.php ./out/config.php
fi
echo 'Combining src and lib'
cat ./src/vzcontrol ./lib/library.php ./src/functions.php | sed '/\/\/_REMOVE_START/,/\/\/_REMOVE_END/d' > ./out/vzcontrol
chmod +x ./out/vzcontrol
echo 'Complete'
